services:
  back:
    build:
      context: .
      dockerfile: back/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - path: back/.env
        required: false
    environment:
      PORT: 3000
    depends_on:
      mongo:
        condition: service_healthy
        required: false # Se o service estiver desligado, nao rompe nada

  mongo:
    image: mongo:8.2
    profiles: ["mongo"] # Opcional, só com --profile mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s

  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - path: front/.env
        required: false
    environment:
      API_PROXY: http://back:3000

volumes:
  mongo-data:
